name: GDLauncher Next CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.3'
      - name: npm run install
        run: |
          yarn install
      - name: npm run release for windows
        if: matrix.os == 'windows-latest' && github.event_name == 'push'
        run: |
          yarn run 
      - name: npm run release for mac and linux
        if: matrix.os != 'windows-latest' || github.event_name != 'push'
        run: |
          yarn run
